# Generated by Django 5.2.1 on 2025-06-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='is_completed',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='progress',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='trainingcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='trainingcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='training/categories/'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='training.enrollment'),
        ),
        migrations.AlterField(
            model_name='trainingcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='duration_hours',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='trainingmodule',
            unique_together={('course', 'order')},
        ),
    ]
