# Generated by Django 5.2.1 on 2025-06-03 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.CharField(help_text='e.g., 1-3 days', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cities', models.TextField(help_text='Comma-separated list of cities')),
                ('min_delivery_days', models.PositiveIntegerField(default=1)),
                ('max_delivery_days', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_weight', models.DecimalField(decimal_places=2, default=0, help_text='Minimum weight in kg', max_digits=8)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum weight in kg', max_digits=8)),
                ('base_cost', models.DecimalField(decimal_places=2, help_text='Base shipping cost in UGX', max_digits=10)),
                ('per_kg_cost', models.DecimalField(decimal_places=2, default=0, help_text='Additional cost per kg in UGX', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['min_weight'],
            },
        ),
    ]
