export interface Product {
  id: number
  name: string
  price: number
  originalPrice?: number
  image: string
  badge?: string
  rating: number
  reviews: number
  category: string
  inStock: boolean
  description: string
  specifications: string[]
  features: string[]
  tags: string[] // Added for better search
}

export const products: Product[] = [
  {
    id: 1,
    name: "Arduino Uno R3",
    price: 85000,
    originalPrice: 95000,
    image: "/images/arduino-uno-r3.svg",
    badge: "Best Seller",
    rating: 4.8,
    reviews: 124,
    category: "Development Boards",
    inStock: true,
    description:
      "The Arduino Uno R3 is a microcontroller board based on the ATmega328P. It's perfect for beginners and professionals alike.",
    specifications: ["ATmega328P microcontroller", "14 digital I/O pins", "6 analog inputs", "USB connection"],
    features: ["Easy to use", "Large community support", "Compatible with shields", "Open source"],
    tags: ["arduino", "microcontroller", "beginner", "prototyping", "atmega328p", "development", "board"],
  },
  {
    id: 2,
    name: "Raspberry Pi 4 Model B 4GB",
    price: 180000,
    originalPrice: 200000,
    image: "/images/raspberry-pi-4b.webp",
    badge: "New",
    rating: 4.9,
    reviews: 89,
    category: "Development Boards",
    inStock: true,
    description: "A powerful single-board computer with 4GB RAM, perfect for IoT projects and learning programming.",
    specifications: ["Quad-core ARM Cortex-A72", "4GB LPDDR4 RAM", "Dual-band WiFi", "Bluetooth 5.0"],
    features: ["4K video output", "USB 3.0 ports", "GPIO pins", "MicroSD card slot"],
    tags: ["raspberry", "pi", "computer", "iot", "linux", "programming", "wifi", "bluetooth"],
  },
  {
    id: 3,
    name: "ESP32 Development Board",
    price: 45000,
    originalPrice: 55000,
    image: "/images/esp32-dev-board.webp",
    badge: "Hot Deal",
    rating: 4.7,
    reviews: 156,
    category: "Microcontrollers",
    inStock: true,
    description: "WiFi and Bluetooth enabled microcontroller perfect for IoT applications.",
    specifications: ["Dual-core processor", "WiFi 802.11 b/g/n", "Bluetooth 4.2", "34 GPIO pins"],
    features: ["Low power consumption", "Built-in WiFi", "Arduino IDE compatible", "Rich peripheral set"],
    tags: ["esp32", "wifi", "bluetooth", "iot", "wireless", "microcontroller", "espressif"],
  },
  {
    id: 4,
    name: "STM32 Nucleo-64 Board",
    price: 120000,
    originalPrice: 135000,
    image: "/images/stm32-nucleo-board.webp",
    badge: "Professional",
    rating: 4.6,
    reviews: 67,
    category: "Development Boards",
    inStock: false,
    description: "Professional development board with ARM Cortex-M4 processor for advanced applications.",
    specifications: ["ARM Cortex-M4 core", "512KB Flash", "128KB RAM", "ST-LINK debugger"],
    features: ["Professional grade", "Advanced debugging", "Real-time performance", "Low power modes"],
    tags: ["stm32", "arm", "cortex", "professional", "debugger", "real-time", "embedded"],
  },
  {
    id: 5,
    name: "DHT22 Temperature Sensor",
    price: 25000,
    originalPrice: 30000,
    image: "/images/dht22-temperature-sensor.webp",
    badge: "",
    rating: 4.5,
    reviews: 203,
    category: "Sensors",
    inStock: true,
    description: "High precision temperature and humidity sensor with digital output.",
    specifications: [
      "Temperature range: -40°C to 80°C",
      "Humidity range: 0-100% RH",
      "Digital signal output",
      "3.3V-5V power",
    ],
    features: ["High accuracy", "Digital output", "Easy to use", "Long-term stability"],
    tags: ["temperature", "humidity", "sensor", "digital", "dht22", "environmental", "monitoring"],
  },
  {
    id: 6,
    name: "HC-SR04 Ultrasonic Sensor",
    price: 15000,
    originalPrice: 18000,
    image: "/images/hc-sr04-ultrasonic-v2.webp",
    badge: "",
    rating: 4.4,
    reviews: 178,
    category: "Sensors",
    inStock: true,
    description: "Ultrasonic distance sensor for measuring distances from 2cm to 400cm.",
    specifications: ["Range: 2cm - 400cm", "Accuracy: 3mm", "Working voltage: 5V", "Working current: 15mA"],
    features: ["Non-contact measurement", "High accuracy", "Easy interface", "Stable performance"],
    tags: ["ultrasonic", "distance", "sensor", "ranging", "hc-sr04", "proximity", "measurement"],
  },
  {
    id: 7,
    name: "NodeMCU ESP8266",
    price: 35000,
    originalPrice: 40000,
    image: "/images/nodemcu-esp8266-v2.webp",
    badge: "Popular",
    rating: 4.6,
    reviews: 245,
    category: "Microcontrollers",
    inStock: true,
    description: "WiFi-enabled microcontroller development board based on ESP8266.",
    specifications: ["ESP8266 WiFi SoC", "4MB Flash memory", "80MHz processor", "17 GPIO pins"],
    features: ["Built-in WiFi", "Arduino IDE support", "Lua scripting", "Low cost"],
    tags: ["nodemcu", "esp8266", "wifi", "iot", "wireless", "lua", "arduino"],
  },
  {
    id: 8,
    name: "Servo Motor SG90",
    price: 18000,
    originalPrice: 22000,
    image: "/images/servo-motor-sg90.jpeg",
    badge: "",
    rating: 4.4,
    reviews: 198,
    category: "Actuators",
    inStock: true,
    description: "Micro servo motor for precise angular positioning in robotics projects.",
    specifications: ["180° rotation", "4.8V-6V operation", "Plastic gears", "20g weight"],
    features: ["Precise control", "Lightweight", "Easy mounting", "Standard connector"],
    tags: ["servo", "motor", "actuator", "robotics", "sg90", "positioning", "control"],
  },
  {
    id: 9,
    name: "LCD 16x2 Display Module",
    price: 30000,
    originalPrice: 35000,
    image: "/images/lcd-16x2-display-v2.jpeg",
    badge: "",
    rating: 4.3,
    reviews: 134,
    category: "Modules",
    inStock: true,
    description: "16x2 character LCD display with blue backlight for text output.",
    specifications: ["16 characters x 2 lines", "HD44780 controller", "5V operation", "Blue backlight"],
    features: ["Clear display", "Easy interface", "Backlight included", "Standard pinout"],
    tags: ["lcd", "display", "module", "text", "character", "backlight", "hd44780"],
  },
  {
    id: 10,
    name: "Breadboard 830 Points",
    price: 12000,
    originalPrice: 15000,
    image: "/images/breadboard-830-points.jpeg",
    badge: "",
    rating: 4.6,
    reviews: 267,
    category: "Tools & Equipment",
    inStock: true,
    description: "Solderless breadboard for prototyping electronic circuits.",
    specifications: ["830 tie points", "2 power rails", "ABS plastic base", "Standard spacing"],
    features: ["Solderless", "Reusable", "Color coded", "Stable connections"],
    tags: ["breadboard", "prototyping", "solderless", "circuit", "testing", "development"],
  },
  {
    id: 11,
    name: "Dupont Jumper Wires Set",
    price: 8000,
    originalPrice: 10000,
    image: "/images/dupont-jumper-wires.webp",
    badge: "",
    rating: 4.2,
    reviews: 156,
    category: "Components",
    inStock: true,
    description: "Premium set of 120 dupont jumper wires for breadboard and module connections.",
    specifications: [
      "120 pieces total",
      "Male-to-male, male-to-female, female-to-female",
      "Multiple colors",
      "22AWG wire",
    ],
    features: ["Color coded", "Flexible", "Good conductivity", "Various lengths", "Dupont connectors"],
    tags: ["jumper", "wires", "connections", "breadboard", "dupont", "colorful", "set"],
  },
  {
    id: 12,
    name: "Resistor Kit 600pcs",
    price: 22000,
    originalPrice: 28000,
    image: "/images/resistor-kit-600pcs-v2.webp",
    badge: "",
    rating: 4.5,
    reviews: 89,
    category: "Components",
    inStock: true,
    description: "Complete resistor kit with 30 different values, 20 pieces each.",
    specifications: ["600 resistors total", "30 different values", "1/4W power rating", "5% tolerance"],
    features: ["Complete set", "Organized storage", "Color coded", "Standard values"],
    tags: ["resistor", "kit", "components", "values", "electronics", "passive", "ohm"],
  },
  {
    id: 13,
    name: "10mm LED Assorted Kit",
    price: 15000,
    originalPrice: 18000,
    image: "/images/10mm-leds-assorted.webp",
    badge: "",
    rating: 4.3,
    reviews: 123,
    category: "Components",
    inStock: true,
    description: "Assorted 10mm LED kit with different colors and high brightness for various projects.",
    specifications: [
      "50 LEDs total",
      "5 different colors",
      "10mm diameter",
      "High brightness",
      "Standard forward voltage",
    ],
    features: ["Multiple colors", "High brightness", "Long lifespan", "Wide viewing angle"],
    tags: ["led", "light", "diode", "colors", "assorted", "kit", "bright", "10mm"],
  },
  {
    id: 14,
    name: "Stepper Motor NEMA17",
    price: 45000,
    originalPrice: 50000,
    image: "/images/stepper-motor-nema17-v2.jpeg",
    badge: "",
    rating: 4.7,
    reviews: 87,
    category: "Actuators",
    inStock: true,
    description: "High precision stepper motor for 3D printers and CNC machines.",
    specifications: ["1.8° step angle", "200 steps/revolution", "12V operation", "NEMA17 standard"],
    features: ["High precision", "Low vibration", "Standard mounting", "Reliable operation"],
    tags: ["stepper", "motor", "nema17", "precision", "cnc", "3d printer", "actuator"],
  },
  {
    id: 15,
    name: "OLED Display 0.96 inch",
    price: 28000,
    originalPrice: 32000,
    image: "/images/oled-display-096-v2.webp",
    badge: "",
    rating: 4.6,
    reviews: 156,
    category: "Modules",
    inStock: true,
    description: "Small OLED display module with I2C interface for compact projects.",
    specifications: ["0.96 inch diagonal", "128x64 resolution", "I2C interface", "3.3V-5V operation"],
    features: ["High contrast", "Low power", "Compact size", "Easy interface"],
    tags: ["oled", "display", "module", "i2c", "small", "compact", "graphics"],
  },
  // NEW PRODUCTS ADDED
  {
    id: 16,
    name: "LDR GL5516 Light Sensor",
    price: 3000,
    originalPrice: 4000,
    image: "/images/ldr-gl5516-sensor.webp",
    badge: "",
    rating: 4.4,
    reviews: 89,
    category: "Sensors",
    inStock: true,
    description: "GL5516 photoresistor for light detection and automatic lighting control projects.",
    specifications: [
      "Resistance range: 5-10kΩ (light) to 0.5-3MΩ (dark)",
      "Peak wavelength: 540nm",
      "Operating temperature: -30°C to +70°C",
      "Response time: 20-30ms",
    ],
    features: ["High sensitivity", "Wide resistance range", "Stable performance", "Low cost"],
    tags: ["ldr", "photoresistor", "light", "sensor", "gl5516", "detection", "automatic"],
  },
  {
    id: 17,
    name: "Soil Moisture Sensor Module",
    price: 12000,
    originalPrice: 15000,
    image: "/images/soil-moisture-sensor.webp",
    badge: "",
    rating: 4.5,
    reviews: 67,
    category: "Sensors",
    inStock: true,
    description: "DFRobot resistive soil moisture sensor for plant monitoring and irrigation systems.",
    specifications: [
      "Operating voltage: 3.3V-5V",
      "Output: Analog and digital",
      "Probe length: 6cm",
      "PCB size: 3cm x 1.5cm",
    ],
    features: ["Corrosion resistant", "Easy to use", "Analog and digital output", "Adjustable sensitivity"],
    tags: ["soil", "moisture", "sensor", "plant", "irrigation", "dfrobot", "agriculture"],
  },
  {
    id: 18,
    name: "LDR Sensor Module (10-Pack)",
    price: 35000,
    originalPrice: 42000,
    image: "/images/ldr-sensor-module.webp",
    badge: "Bulk Pack",
    rating: 4.6,
    reviews: 45,
    category: "Sensors",
    inStock: true,
    description: "Pack of 10 LDR sensor modules with built-in comparator and adjustable sensitivity.",
    specifications: [
      "Operating voltage: 3.3V-5V",
      "Digital and analog output",
      "Adjustable threshold",
      "LED indicators",
    ],
    features: ["Built-in comparator", "Adjustable sensitivity", "LED status indicators", "Ready-to-use modules"],
    tags: ["ldr", "module", "bulk", "pack", "light", "sensor", "comparator", "digital"],
  },
  {
    id: 19,
    name: "5V Relay Module",
    price: 8000,
    originalPrice: 10000,
    image: "/images/5v-relay-module.webp",
    badge: "",
    rating: 4.7,
    reviews: 134,
    category: "Modules",
    inStock: true,
    description: "Single channel 5V relay module for controlling high-power devices with microcontrollers.",
    specifications: [
      "Control voltage: 5V",
      "Contact rating: 10A 250VAC, 10A 30VDC",
      "Trigger: Low level",
      "LED indicator",
    ],
    features: ["Optocoupler isolation", "High current switching", "LED status indicator", "Screw terminals"],
    tags: ["relay", "module", "5v", "switch", "control", "high", "power", "isolation"],
  },
  {
    id: 20,
    name: "PIR Motion Sensor HC-SR501",
    price: 8500,
    originalPrice: 11000,
    image: "/images/pir-motion-sensor.webp",
    badge: "",
    rating: 4.5,
    reviews: 178,
    category: "Sensors",
    inStock: true,
    description: "Passive infrared motion sensor for detecting human movement in security and automation projects.",
    specifications: [
      "Detection range: 3-7 meters",
      "Detection angle: 120°",
      "Operating voltage: 5V-20V",
      "Output: Digital",
    ],
    features: ["Adjustable sensitivity", "Adjustable delay time", "Wide detection angle", "Low power consumption"],
    tags: ["pir", "motion", "sensor", "hc-sr501", "security", "detection", "infrared", "movement"],
  },
  {
    id: 21,
    name: "Radxa Rock 4C Plus SBC",
    price: 165000,
    originalPrice: 185000,
    image: "/images/radxa-rock-4c-plus.webp",
    badge: "Alternative SBC",
    rating: 4.4,
    reviews: 23,
    category: "Development Boards",
    inStock: true,
    description: "Powerful single-board computer with RK3399-T processor, great alternative to Raspberry Pi.",
    specifications: ["RK3399-T hexa-core processor", "4GB LPDDR4 RAM", "32GB eMMC storage", "WiFi 5 & Bluetooth 5.0"],
    features: ["4K video output", "USB 3.0 ports", "40-pin GPIO", "Android and Linux support"],
    tags: ["radxa", "rock", "sbc", "single", "board", "computer", "rk3399", "alternative"],
  },
  // NEW PRODUCTS BATCH 2
  {
    id: 22,
    name: "DHT11 Temperature Sensor",
    price: 15000,
    originalPrice: 18000,
    image: "/images/dht11-sensor.webp",
    badge: "",
    rating: 4.3,
    reviews: 156,
    category: "Sensors",
    inStock: true,
    description: "Basic temperature and humidity sensor module for environmental monitoring projects.",
    specifications: [
      "Temperature range: 0°C to 50°C",
      "Humidity range: 20-90% RH",
      "Digital signal output",
      "3.3V-5V power supply",
    ],
    features: ["Low cost", "Digital output", "Calibrated", "Long transmission distance"],
    tags: ["temperature", "humidity", "sensor", "digital", "dht11", "basic", "monitoring"],
  },
  {
    id: 23,
    name: "DHT22 Sensor Module Complete",
    price: 28000,
    originalPrice: 32000,
    image: "/images/dht22-sensor-module.webp",
    badge: "Premium",
    rating: 4.7,
    reviews: 89,
    category: "Sensors",
    inStock: true,
    description: "High precision DHT22 sensor module with connecting wires and pull-up resistor included.",
    specifications: [
      "Temperature range: -40°C to 80°C",
      "Humidity range: 0-100% RH",
      "±0.5°C accuracy",
      "Complete module with wires",
    ],
    features: ["High precision", "Pre-wired", "Pull-up resistor included", "Ready to use"],
    tags: ["dht22", "temperature", "humidity", "precision", "module", "complete", "wired"],
  },
  {
    id: 24,
    name: "Full-Size Solderable Breadboards (3-Pack)",
    price: 45000,
    originalPrice: 55000,
    image: "/images/full-size-breadboards.webp",
    badge: "3-Pack",
    rating: 4.6,
    reviews: 78,
    category: "Tools & Equipment",
    inStock: true,
    description: "Set of 3 full-size solderable breadboards for permanent prototype projects.",
    specifications: ["3 breadboards per pack", "Full-size format", "Solderable PCB", "Standard 0.1 inch spacing"],
    features: ["Permanent connections", "Professional quality", "Multiple boards", "Solderable"],
    tags: ["breadboard", "solderable", "pcb", "prototype", "permanent", "full-size", "pack"],
  },
  {
    id: 25,
    name: "HC-SR04 Ultrasonic Distance Sensor",
    price: 16000,
    originalPrice: 20000,
    image: "/images/hc-sr04-ultrasonic.webp",
    badge: "",
    rating: 4.5,
    reviews: 267,
    category: "Sensors",
    inStock: true,
    description: "Ultrasonic distance measurement sensor for robotics and automation projects.",
    specifications: ["Range: 2cm to 400cm", "Accuracy: ±3mm", "Working voltage: 5V DC", "Working current: 15mA"],
    features: ["Non-contact measurement", "High accuracy", "Easy to use", "Wide range"],
    tags: ["ultrasonic", "distance", "sensor", "hc-sr04", "measurement", "robotics", "ranging"],
  },
  {
    id: 26,
    name: "Metal Film Resistor Kit (1800pcs)",
    price: 35000,
    originalPrice: 42000,
    image: "/images/resistor-kit-chanzon.webp",
    badge: "Complete Kit",
    rating: 4.8,
    reviews: 145,
    category: "Components",
    inStock: true,
    description: "Comprehensive resistor kit with 60 values, 30 pieces each, organized in storage case.",
    specifications: ["1800 resistors total", "60 different values", "0.25W power rating", "1% tolerance"],
    features: ["Metal film precision", "Organized storage", "Complete value range", "Color chart included"],
    tags: ["resistor", "kit", "metal", "film", "precision", "components", "1800", "organized"],
  },
  {
    id: 27,
    name: "STM32F103 Nucleo-64 Board",
    price: 125000,
    originalPrice: 140000,
    image: "/images/stm32f103-nucleo.webp",
    badge: "Professional",
    rating: 4.7,
    reviews: 56,
    category: "Development Boards",
    inStock: true,
    description: "STM32F103RBT6 Nucleo-64 development board with ST-LINK debugger for professional development.",
    specifications: [
      "ARM Cortex-M3 core at 72MHz",
      "128KB Flash, 20KB SRAM",
      "Arduino Uno V3 connectivity",
      "ST morpho extension pins",
    ],
    features: ["Embedded ST-LINK/V2-1 debugger", "Arduino compatible", "Mbed enabled", "Professional grade"],
    tags: ["stm32", "nucleo", "arm", "cortex", "m3", "professional", "debugger", "st-link"],
  },
  {
    id: 28,
    name: "STM32F405 Thing Plus Board",
    price: 85000,
    originalPrice: 95000,
    image: "/images/stm32f405-thing-plus.webp",
    badge: "SparkFun",
    rating: 4.5,
    reviews: 34,
    category: "Development Boards",
    inStock: true,
    description: "SparkFun STM32F405 Thing Plus board with ARM Cortex-M4 processor for advanced projects.",
    specifications: ["ARM Cortex-M4F core at 168MHz", "1MB Flash, 192KB SRAM", "USB-C connector", "Qwiic connector"],
    features: ["High performance", "USB-C", "Qwiic ecosystem", "Compact design"],
    tags: ["stm32f405", "sparkfun", "thing", "plus", "cortex", "m4", "usb-c", "qwiic"],
  },
  {
    id: 29,
    name: "Elegoo Breadboard Set (3-Pack)",
    price: 25000,
    originalPrice: 30000,
    image: "/images/elegoo-breadboards.webp",
    badge: "Value Pack",
    rating: 4.4,
    reviews: 189,
    category: "Tools & Equipment",
    inStock: true,
    description: "Set of 3 high-quality solderless breadboards for prototyping and circuit testing.",
    specifications: ["3 breadboards per pack", "830 tie points each", "Self-adhesive backing", "Color-coded rails"],
    features: ["Solderless design", "Reusable", "Self-adhesive", "Multiple boards"],
    tags: ["elegoo", "breadboard", "solderless", "prototyping", "3-pack", "adhesive", "testing"],
  },
  {
    id: 30,
    name: "NodeMCU ESP8266 WiFi Module",
    price: 38000,
    originalPrice: 45000,
    image: "/images/nodemcu-esp8266.webp",
    badge: "WiFi Enabled",
    rating: 4.6,
    reviews: 234,
    category: "Microcontrollers",
    inStock: true,
    description: "NodeMCU development board with ESP8266 WiFi module for IoT applications.",
    specifications: ["ESP8266 WiFi SoC", "4MB Flash memory", "80MHz processor", "17 GPIO pins"],
    features: ["Built-in WiFi", "Arduino IDE support", "Lua scripting", "IoT ready"],
    tags: ["nodemcu", "esp8266", "wifi", "iot", "lua", "arduino", "wireless", "module"],
  },
  {
    id: 31,
    name: "ESP8266 NodeMCU Breakout Board",
    price: 22000,
    originalPrice: 28000,
    image: "/images/esp8266-breakout.webp",
    badge: "Breakout",
    rating: 4.3,
    reviews: 67,
    category: "Modules",
    inStock: true,
    description: "ESP8266 NodeMCU breakout board with screw terminals for easy connections.",
    specifications: [
      "ESP8266 compatibility",
      "Screw terminal blocks",
      "0.9, 1.0, 1.1 inch pitch support",
      "GPIO breakout",
    ],
    features: ["Screw terminals", "Easy connections", "Multiple pitch support", "GPIO access"],
    tags: ["esp8266", "nodemcu", "breakout", "screw", "terminal", "connections", "gpio", "board"],
  },
  {
    id: 32,
    name: "Waterproof Temperature Sensor DS18B20",
    price: 18000,
    originalPrice: 22000,
    image: "/images/waterproof-temperature-sensor.jpeg",
    badge: "Waterproof",
    rating: 4.7,
    reviews: 145,
    category: "Sensors",
    inStock: true,
    description:
      "Waterproof digital temperature sensor with stainless steel probe for liquid and outdoor temperature monitoring.",
    specifications: [
      "Temperature range: -55°C to +125°C",
      "Accuracy: ±0.5°C",
      "Waterproof stainless steel probe",
      "3-wire interface",
      "3.0V to 5.5V power supply",
    ],
    features: ["Waterproof design", "High accuracy", "Digital output", "Long cable", "Stainless steel probe"],
    tags: ["temperature", "sensor", "waterproof", "ds18b20", "digital", "probe", "liquid", "outdoor"],
  },
  {
    id: 33,
    name: "MQ-135 Air Quality Gas Sensor Module",
    price: 12000,
    originalPrice: 15000,
    image: "/images/mq135-air-quality-sensor.webp",
    badge: "Air Quality",
    rating: 4.4,
    reviews: 98,
    category: "Sensors",
    inStock: true,
    description:
      "MQ-135 gas sensor module for detecting air quality, smoke, alcohol, CO2, ammonia and other harmful gases.",
    specifications: [
      "Detection gases: NH3, NOx, alcohol, benzene, smoke, CO2",
      "Operating voltage: 5V DC",
      "Analog and digital output",
      "Adjustable sensitivity",
      "Heating time: 20 seconds",
    ],
    features: [
      "Multiple gas detection",
      "Analog and digital output",
      "Adjustable threshold",
      "LED indicators",
      "Easy interface",
    ],
    tags: ["air", "quality", "gas", "sensor", "mq135", "smoke", "alcohol", "co2", "ammonia", "detection"],
  },
]

// Temporary categories until we connect to Django
export const categories = [
  "All",
  "Microcontrollers",
  "Development Boards",
  "Sensors",
  "Displays",
  "Motors & Actuators",
  "Power Supplies",
  "Cables & Connectors",
  "Tools & Equipment",
  "Kits & Modules",
]

// This will be replaced with Django API calls
export const sampleProducts = [
  {
    id: 1,
    name: "Arduino Uno R3",
    price: 25000,
    image: "/placeholder.svg?height=200&width=200",
    category: "Microcontrollers",
    description: "The classic Arduino Uno R3 development board",
  },
  {
    id: 2,
    name: "Raspberry Pi 4 Model B",
    price: 180000,
    image: "/placeholder.svg?height=200&width=200",
    category: "Development Boards",
    description: "Latest Raspberry Pi with 4GB RAM",
  },
]

export function searchProducts(query: string, products: Product[]): Product[] {
  if (!query.trim()) return products

  const searchTerm = query.toLowerCase().trim()
  const searchWords = searchTerm.split(" ").filter((word) => word.length > 0)

  return products.filter((product) => {
    // Create searchable text from all product fields
    const searchableText = [
      product.name,
      product.category,
      product.description,
      ...product.features,
      ...product.specifications,
      ...product.tags,
    ]
      .join(" ")
      .toLowerCase()

    // Check if any search word matches
    return (
      searchWords.some(
        (word) =>
          searchableText.includes(word) ||
          // Fuzzy matching for common typos
          searchableText.includes(word.replace("o", "0")) ||
          searchableText.includes(word.replace("0", "o")) ||
          searchableText.includes(word.replace("i", "1")) ||
          searchableText.includes(word.replace("1", "i")),
      ) ||
      // Exact phrase matching
      searchableText.includes(searchTerm)
    )
  })
}

export function getProductsByCategory(category: string, products: Product[]): Product[] {
  if (!category || category === "All") return products
  return products.filter((product) => product.category === category)
}

export function getProductById(id: number, products: Product[]): Product | undefined {
  return products.find((product) => product.id === id)
}
