# Generated by Django 4.2.7 on 2025-07-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/'),
        ),
        migrations.AddField(
            model_name='dailydeal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/'),
        ),
        migrations.AddField(
            model_name='smallitempackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deals/'),
        ),
    ]
