# Generated by Django 5.2.1 on 2025-07-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google.com', 'Google'), ('firebase', 'Firebase')], default='email', max_length=50),
        ),
    ]
